cargo-features = ["edition2024"]
[package]
name = "slay_the_spire"
version = "0.1.0"
edition = "2024"

[dependencies]
rand = "0.9.1"
clap = { version = "4.4", features = ["derive"] }

[[bin]]
name = "game"
path = "src/bin/game.rs"

[[bin]]
name = "battle"
path = "src/bin/battle.rs"
